repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-added-large-files
    exclude: ^models/
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^models/
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: ^models/
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.7.0
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
